#!/bin/bash

# Setup script for iOS builds to handle Sentry configuration
# This script is run during EAS Build to ensure proper environment variables

echo "Setting up iOS build environment..."

# Export Sentry environment variables to disable uploads
export SENTRY_DISABLE_AUTO_UPLOAD=true
export SENTRY_ALLOW_FAILURE=true

# Create or update .xcode.env.local with Sentry configuration
cat > ios/.xcode.env.local << EOF
# Auto-generated by setup-ios-build.sh
export NODE_BINARY=\$(command -v node)
export SENTRY_DISABLE_AUTO_UPLOAD=true
export SENTRY_ALLOW_FAILURE=true
EOF

echo "SENTRY_DISABLE_AUTO_UPLOAD set to: $SENTRY_DISABLE_AUTO_UPLOAD"
echo "SENTRY_ALLOW_FAILURE set to: $SENTRY_ALLOW_FAILURE"
echo "iOS build environment setup complete."